[chipflow]
project_name = "sram"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.clocks]
default = 'sys_clk'

[chipflow.resets]
default = 'sys_rst_n'

[chipflow.silicon]
process = "ihp_sg13g2"
package = "pga144"
