[chipflow.steps]
sim = "design.steps.sim:MySimStep"
board = "design.steps.board:MyBoardStep"
silicon = "design.steps.silicon:MySiliconStep"
software = "design.steps.software:MySoftwareStep"

[chipflow.silicon]
process = "sky130"
pad_ring = "caravel"

[chipflow.silicon.pads]
sys_clk   = { type = "clk", loc = "0" }
sys_rstn  = { type = "i",   loc = "1" }
en        = { type = "i",   loc = "2" }
ovf       = { type = "o",   loc = "3" }
limit_0   = { type = "i",   loc = "4" }
limit_1   = { type = "i",   loc = "5" }
limit_2   = { type = "i",   loc = "6" }
limit_3   = { type = "i",   loc = "7" }
limit_4   = { type = "i",   loc = "8" }
limit_5   = { type = "i",   loc = "9" }
limit_6   = { type = "i",   loc = "10" }
limit_7   = { type = "i",   loc = "11" }
count_0   = { type = "o",   loc = "12" }
count_1   = { type = "o",   loc = "13" }
count_2   = { type = "o",   loc = "14" }
count_3   = { type = "o",   loc = "15" }
count_4   = { type = "o",   loc = "16" }
count_5   = { type = "o",   loc = "17" }
count_6   = { type = "o",   loc = "18" }
count_7   = { type = "o",   loc = "19" }
#jtag_tck  = { type = "i",   loc = "33" }
#jtag_tms  = { type = "i",   loc = "34" }
#jtag_tdi  = { type = "i",   loc = "35" }
#jtag_tdo  = { type = "o",   loc = "36" }

