[chipflow]
project_name = "upcounter"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.clocks]
default = 'sys_clk'

[chipflow.resets]
default = 'sys_rst_n'

[chipflow.silicon]
process = "ihp_sg13g2"
package = "block"

[chipflow.silicon.block]
width = 5
height = 5

[chipflow.silicon.pads]
# System (no fixed locations for blocks — auto-allocated)
sys_clk   = { type = "clock" }
sys_rst_n = { type = "reset" }
