name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      backend_version:
        description: 'chipflow-backend version (e.g., branch-main, branch-feature, or a git ref)'
        required: false
        default: 'branch-main'
        type: string
  repository_dispatch:
    types: [run-tests]

jobs:

  build-upcounter:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --no-sources --no-dev

      - name: Build upcounter
        run: |
          uv run chipflow pin lock
          uv run chipflow silicon prepare
          uv run chipflow silicon submit --wait
        env:
          CHIPFLOW_BACKEND_VERSION: ${{ inputs.backend_version || github.event.client_payload.backend_version || 'branch-main' }}
          CHIPFLOW_ROOT: "upcounter"
          CHIPFLOW_API_ORIGIN: 'https://build.staging.chipflow.com'
          CHIPFLOW_API_KEY: ${{ secrets.CHIPFLOW_API_KEY }}

  build-rom:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --no-sources --no-dev

      - name: Build rom
        run: |
          uv run chipflow pin lock
          uv run chipflow silicon prepare
          uv run chipflow silicon submit --wait
        env:
          CHIPFLOW_BACKEND_VERSION: ${{ inputs.backend_version || github.event.client_payload.backend_version || 'branch-main' }}
          CHIPFLOW_ROOT: "rom"
          CHIPFLOW_API_ORIGIN: 'https://build.staging.chipflow.com'
          CHIPFLOW_API_KEY: ${{ secrets.CHIPFLOW_API_KEY }}

  build-sram:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --no-sources --no-dev

      - name: Build sram
        run: |
          uv run chipflow pin lock
          uv run chipflow silicon prepare
          uv run chipflow silicon submit --wait
        env:
          CHIPFLOW_BACKEND_VERSION: ${{ inputs.backend_version || github.event.client_payload.backend_version || 'branch-main' }}
          CHIPFLOW_ROOT: "sram"
          CHIPFLOW_API_ORIGIN: 'https://build.staging.chipflow.com'
          CHIPFLOW_API_KEY: ${{ secrets.CHIPFLOW_API_KEY }}
